[build]
builder = "nixpacks"

[deploy]
startCommand = "python run.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"

[env]
PYTHON_VERSION = "3.11"
PORT = "8000"
HOST = "0.0.0.0"
PIP_NO_CACHE_DIR = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"